[package]
name = "aip-man"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "4.1.1", features = [ "derive" ] }
reqwest = { version = "0.11.13", features = [ "blocking" ] }
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0.91"
dirs = "4.0.0"
version-compare = "0.1.1"
